### ISSUE TITLE
firehose closing with error at random

### ISSUE THREAD

**Issue by gabboman** [skyware-js/firehose#2]
I get this error on console. Have I angered the gods with my hubris?

```
node:events:511
    throw err; // Unhandled 'error' event
    ^

Error [ERR_UNHANDLED_ERROR]: Unhandled error. ({
  cursor: '3383832648',
  error: Error: Invalid header received
      at parseHeader (file:///Users/gabriel/workspace/wafrn/node_modules/@skyware/firehose/dist/index.js:166:15)
      at Firehose.parseMessage (file:///Users/gabriel/workspace/wafrn/node_modules/@skyware/firehose/dist/index.js:107:27)
      at WebSocket.<anonymous> (file:///Users/gabriel/workspace/wafrn/node_modules/@skyware/firehose/dist/index.js:35:38)
      at WebSocket.emit (node:events:520:28)
      at Receiver.receiverOnMessage (/Users/gabriel/workspace/wafrn/node_modules/ws/lib/websocket.js:1220:20)
      at Receiver.emit (node:events:520:28)
      at Receiver.dataMessage (/Users/gabriel/workspace/wafrn/node_modules/ws/lib/receiver.js:569:14)
      at Receiver.getData (/Users/gabriel/workspace/wafrn/node_modules/ws/lib/receiver.js:496:10)
      at Receiver.startLoop (/Users/gabriel/workspace/wafrn/node_modules/ws/lib/receiver.js:167:16)
      at Receiver._write (/Users/gabriel/workspace/wafrn/node_modules/ws/lib/receiver.js:94:10)
      at writeOrBuffer (node:internal/streams/writable:570:12)
      at _write (node:internal/streams/writable:499:10)
      at Writable.write (node:internal/streams/writable:508:10)
      at TLSSocket.socketOnData (/Users/gabriel/workspace/wafrn/node_modules/ws/lib/websocket.js:1355:35)
      at TLSSocket.emit (node:events:520:28)
      at addChunk (node:internal/streams/readable:559:12)
})
    at Firehose.emit (node:events:509:17)
    at WebSocket.<anonymous> (file:///Users/gabriel/workspace/wafrn/node_modules/@skyware/firehose/dist/index.js:64:22)
    at WebSocket.emit (node:events:520:28)
    at Receiver.receiverOnMessage (/Users/gabriel/workspace/wafrn/node_modules/ws/lib/websocket.js:1220:20)
    at Receiver.emit (node:events:520:28)
    at Receiver.dataMessage (/Users/gabriel/workspace/wafrn/node_modules/ws/lib/receiver.js:569:14)
    at Receiver.getData (/Users/gabriel/workspace/wafrn/node_modules/ws/lib/receiver.js:496:10)
    at Receiver.startLoop (/Users/gabriel/workspace/wafrn/node_modules/ws/lib/receiver.js:167:16)
    at Receiver._write (/Users/gabriel/workspace/wafrn/node_modules/ws/lib/receiver.js:94:10)
    at writeOrBuffer (node:internal/streams/writable:570:12)
    at _write (node:internal/streams/writable:499:10)
    at Writable.write (node:internal/streams/writable:508:10)
    at TLSSocket.socketOnData (/Users/gabriel/workspace/wafrn/node_modules/ws/lib/websocket.js:1355:35)
    at TLSSocket.emit (node:events:520:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3) {
  code: 'ERR_UNHANDLED_ERROR',
  context: {
    cursor: '3383832648',
    error: Error: Invalid header received
        at parseHeader (file:///Users/gabriel/workspace/wafrn/node_modules/@skyware/firehose/dist/index.js:166:15)
        at Firehose.parseMessage (file:///Users/gabriel/workspace/wafrn/node_modules/@skyware/firehose/dist/index.js:107:27)
        at WebSocket.<anonymous> (file:///Users/gabriel/workspace/wafrn/node_modules/@skyware/firehose/dist/index.js:35:38)
        at WebSocket.emit (node:events:520:28)
        at Receiver.receiverOnMessage (/Users/gabriel/workspace/wafrn/node_modules/ws/lib/websocket.js:1220:20)
        at Receiver.emit (node:events:520:28)
        at Receiver.dataMessage (/Users/gabriel/workspace/wafrn/node_modules/ws/lib/receiver.js:569:14)
        at Receiver.getData (/Users/gabriel/workspace/wafrn/node_modules/ws/lib/receiver.js:496:10)
        at Receiver.startLoop (/Users/gabriel/workspace/wafrn/node_modules/ws/lib/receiver.js:167:16)
        at Receiver._write (/Users/gabriel/workspace/wafrn/node_modules/ws/lib/receiver.js:94:10)
        at writeOrBuffer (node:internal/streams/writable:570:12)
        at _write (node:internal/streams/writable:499:10)
        at Writable.write (node:internal/streams/writable:508:10)
        at TLSSocket.socketOnData (/Users/gabriel/workspace/wafrn/node_modules/ws/lib/websocket.js:1355:35)
        at TLSSocket.emit (node:events:520:28)
        at addChunk (node:internal/streams/readable:559:12)
  }
}

Node.js v22.8.0
```

**Comment by futurGH** [comment]
Relay's been wonky with all the traffic today, you can handle the `error` and `websocketError` events to prevent it from being thrown.
